main: Assignment5.cpp CommunicationNetwork.o
	g++ -std=c++11 -o main Assignment5.cpp CommunicationNetwork.o

WordAnalysis.o: CommunicationNetwork.cpp CommunicationNetwork.h
	g++ -std=c++11 -c CommunicationNetwork.cpp
